export const MOCKS = [
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108726d00',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title:
      'Spider-Man: No Way HomeSpider-Man: No Way HomeSpider-Man: No Way HomeWay HomeSpider-Man: No Way HomeWay HomeSpider-Man: No Way HomeWay HomeSpider-Man: No Way HomeWay HomeSpider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108726040',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108s726050',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'stt108726040',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108rew726050',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108gre726040',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt1087fwef26050',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108hzt726040',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108726tre050',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt10rew8726040',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt10872rewrewr6050',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108724324326040',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt108764564526050',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt176576508726040',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
  {
    contentRating: 'PG-13',
    description: '(2021)',
    genreList: [],
    genres: 'Action, Adventure, Fantasy',
    id: 'tt1087utzuzt26050',
    imDbRating: '8.4',
    imDbRatingVotes: '599652',
    image:
      'https://imdb-api.com/images/original/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg',
    metacriticRating: '71',
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    runtimeStr: '148 min',
    starList: [],
    stars:
      'Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon',
    title: 'Spider-Man: No Way Home',
  },
]
